### ISSUE TITLE
1日停止作業DAY 2023/XX/XX

### ISSUE THREAD

**Issue by unchama** [GiganticMinecraft/seichi_infra#842]
# TODO
- [x] update synology CSI Driver
- [x] update synology NAS firmware
- [x] update k8s version to 1.26
- [x] HOKORI Busters
- [x] replace 10G-Switch(UniFi Switch Pro Aggregation)
  - [x] スイッチの段に置きたいので代わりにNTPサーバーをNASの段に逃す
- [ ] 電源タップ1個をraritan PDUへ変更
  - 8口の内訳
    - [x] unchama-sv-prox02
    - [x] unchama-sv-prox04
    - [x] unchama-sv-prox05
    - [ ] unchama-sv-dt2
    - [ ] ssh-forward-02
    - [ ] UniFi Switch Pro Aggregation
    - empty
    - empty

**Comment by unchama** [comment]
raritan PDUをどこにおくかまだ決まってない

**Comment by unchama** [comment]
これはとっくにおわっているのでしめる
